### ISSUE TITLE
Having issue running the flutter project 

### ISSUE THREAD

**Issue by Azizadx** [nebiyuelias1/phison-realestate#137]
there is two file inside lib/ how should i start the flutter run

**Comment by Azizadx** [comment]
you can write the steps here neba

**Comment by Azizadx** [comment]
![Screenshot 2023-01-12 at 2 36 43 AM](https://user-images.githubusercontent.com/45791956/211940987-d7fc93da-baf1-4aaf-a14f-9119d2441129.png)
![Screenshot 2023-01-12 at 2 36 54 AM](https://user-images.githubusercontent.com/45791956/211941016-b4091d9f-a5c1-4b00-9ca8-72e11f9e9156.png)

**Comment by nebiyuelias1** [comment]
Are you inside the **lib** directory? Why does it say the target is not found? Because I can see it in the screenshot. Make sure you're inside the lib directory and then the command you used should work.

**Comment by Azizadx** [comment]
am inside the lib directory is not working it say
 that main.dart is not found 
 
![Screenshot 2023-01-12 at 7 25 10 PM](https://user-images.githubusercontent.com/45791956/212123725-df959e79-d698-428a-aee8-b45e8d75e989.png)

**Comment by Azizadx** [comment]
also when i open the project in xcode it is the same

**Comment by nebiyuelias1** [comment]
Ok I see the problem. There is no main.dart file anymore. So you have to
use main_dev.dart

**Comment by Azizadx** [comment]
it is the same 
![Screenshot 2023-01-12 at 2 30 38 AM](https://user-images.githubusercontent.com/45791956/212151395-7f8e7636-93fa-4b45-a389-8869076c65a1.png)

**Comment by Azizadx** [comment]
am I missing to install or to run like should i run the backend

**Comment by nebiyuelias1** [comment]
No, that's not required. This is really strange. I see a weird output after you run the flutter run command. Why does it change the working directory?
Ok here's what I suggest go back to the root directory and then use the following command instead:
```
flutter run lib/main_dev.dart
```

**Comment by Azizadx** [comment]
it worked
